Repository hashicorp/consul-esm, pull requests merged in 2020-06, with the labels that each got.

#63 Bloomberg PR: Non-telemetry improvements
  .gitignore
  README.md
  agent.go
  agent_test.go
  check.go
  check_test.go
  config.go
  config_test.go
  coordinate.go
  coordinate_test.go
  go.mod
  go.sum
  leader.go
  main.go
Labels: enhancement

#62 Add consul version compatibility check on startup
  agent.go
  agent_test.go
  go.mod
  go.sum
  main.go
  version/version.go
  version/version_test.go
Labels: enhancement

#68 Fix issue where consul esm can generate spurious updates
  check.go
Labels: bug

#66 Update README.md to include documentation on required ACL policy rules
  README.md
Labels: documentation
